#%RAML 1.0 NamedExample
value:
  {
  "data": [{
      "applicationId": "linkgroup.fundadmin.membercorrespondencewidget",
      "applicationPath": "/linkgroup.fundadmin.membercorrespondencewidget",
      "parentApplicationId": "linkgroup.fundadmin",
      "resourceId": 18,
      "resourceName": "correspondencewidget",
      "resourcePath": "/correspondencewidget",
      "entityId": "WidgetDefault",
      "actionTypeId": 1,
      "actionTypeName": "view",
      "accessTypeId": 1,
      "accessTypeName": "allow"
    }, {
      "applicationId": "linkgroup.fundadmin.membercorrespondencewidget",
      "applicationPath": "/linkgroup.fundadmin.membercorrespondencewidget",
      "parentApplicationId": "linkgroup.fundadmin",
      "resourceId": 19,
      "resourceName": "thing",
      "resourcePath": "/correspondencewidget/thing",
      "parentResourceId": 18,
      "entityId": "WidgetDefault",
      "actionTypeId": 1,
      "actionTypeName": "view",
      "accessTypeId": 1,
      "accessTypeName": "allow"
    }
  ]
}