#%RAML 1.0 Library
usage:
types:
  AuthorizationRule:
    properties:
      applicationId: string
      applicationPath: string
      parentApplicationId?: string
      resourceId: integer
      resourceName: string
      resourcePath: string
      parentResourceId?: integer
      entityId: string
      actionTypeId: integer
      actionTypeName: string
      accessTypeId: integer
      accessTypeName: string  