#%RAML 1.0 NamedExample
value:
   {
    "data": {
      "investmentChoiceTypes": [{
          "code": "PERCENTAGE",
          "description": "Percentage"
        }, {
          "code": "HIERARCHY",
          "description": "Hierarchy"
        }, {
          "code": "PRORATA",
          "description": "Pro-rata"
        }, {
          "code": "HIGHESTBALANCE",
          "description": "Highest balance"
        }
      ]
    }
   }