#%RAML 1.0 NamedExample
value:
  {
    "data": [
      {
        "key" : "Investments_InvestmentEnquiry_CurrentIntroHeader",
        "value" : "Your Investments"
      },
      {
        "key" : "Investments_InvestmentEnquiry_EditIntroHeader",
        "value" : "Change Your Investments"
      },
      {
        "key" : "Investments_InvestmentEnquiry_FutureSwitchEffectiveHeader",
        "value" : "Future Switch Effective [[FUTURE_DATE]]"
      },
      {
        "key" : "Investments_InvestmentEnquiry_BalanceSwitchEffectiveHeader",
        "value" : "Balance Switch Effective [[BALANCE_DATE]]"
      }
    ] 
  }
