#%RAML 1.0 NamedExample
# member-investments-widget-api-types.PostSwitchResponse
value:
  {
    data: {
      investmentSwitches: [
        {
          transactionId: 123,
          effectiveDate: '2017-12-31'
        }
      ]
    }
  }
      