#%RAML 1.0 NamedExample
value:
  {
    "newSwitch":
    {
      "balanceSplit":
      [
        {
          "investmentOptionId": "test",
          "percentage": 30
        }
      ],
      "futureTransactions":
      [
        {
          "investmentOptionId": "test",
          "investmentSetId": "n/a",
          "percentage": 30
        }        
      ],
      "drawdown":
      {
        "drawdownMethod": "HIGHESTBALANCE",
        "investmentOptions":
        [
          {
            "investmentOptionId": "test",
            "percentage": 30
          } 
        ]
      }
    }
  }