#%RAML 1.0 NamedExample
value:
  {
    "updateSwitch": {
      "balanceSplit": [
      ],
      "futureTransactions": [{
          "investmentOptionId": "",
          "investmentSetId": "",
          "percentage": 50
        }
      ],
      "drawdown": {
        "drawdownMethod": "HIGHESTBALANCE",
        "investmentOptions": [
        ]
      }
    }
  }